// Minimal TypeScript bindings matching backend/main.mo
// In a real setup this file would be generated by `dfx generate backend`.

export type LevelProgress = {
  completed: boolean;
  lastUpdated: bigint;
};

export type UserProgress = {
  level1: LevelProgress;
  level2: LevelProgress;
  level3: LevelProgress;
};

export type UserProfile = {
  name: string;
};

export interface BackendActor {
  // User profile
  getCallerUserProfile: () => Promise<UserProfile | null>;
  getUserProfile: (user: string) => Promise<UserProfile | null>;
  saveCallerUserProfile: (profile: UserProfile) => Promise<void>;

  // Progress
  markLevelCompleted: (level: bigint) => Promise<void>;
  getUserProgress: () => Promise<UserProgress>;
  resetUserProgress: () => Promise<void>;
  isLevelCompleted: (level: bigint) => Promise<boolean>;
}


